[package]
name = "retroshare_compat"
version = "0.1.0"
authors = ["sehraf <sehraf42@gmail.com>"]
edition = "2018"

[features]

[dependencies]
sequoia-openpgp = "^0"
# retroshare_compat_derive = { path = "proc_macro" }
serde = { version = "1.0", features = ["derive"] }
byteorder = "^1"
hex = "^0"